import { api, demoMode } from "./api.js";
import { dashboardData as demoDashboard, inventory as demoInventory, sales as demoSales, customers as demoCustomers } from "./demo-data.js";

const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const money = (cents = 0, digits = 2) => new Intl.NumberFormat("hr-HR", { style:"currency", currency:"EUR", minimumFractionDigits:digits, maximumFractionDigits:digits }).format(Number(cents) / 100);
const number = (value = 0) => new Intl.NumberFormat("hr-HR", { maximumFractionDigits: 1 }).format(Number(value));
const esc = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));

const icons = {
  home:'<path d="m3 10 9-7 9 7v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 21v-8h6v8"/>',
  box:'<path d="m21 8-9 5-9-5 9-5z"/><path d="m3 8 9 5 9-5v9l-9 5-9-5z"/><path d="M12 13v9"/>',
  boxPlus:'<path d="m16 5-4-2-9 5 9 5 9-5-2-1"/><path d="M3 8v9l9 5 5-2.8M12 13v9"/><path d="M19 12v6m-3-3h6"/>',
  bag:'<path d="M6 8h12l1 13H5z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/>',
  tag:'<path d="M20 13 13 20a2 2 0 0 1-3 0l-7-7V3h10l7 7a2 2 0 0 1 0 3z"/><circle cx="8" cy="8" r="1"/>',
  users:'<path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/><path d="M20 8v6m-3-3h6"/>',
  receipt:'<path d="M6 2h12v20l-3-2-3 2-3-2-3 2z"/><path d="M9 7h6m-6 4h6m-6 4h3"/>',
  chart:'<path d="M4 19V9m6 10V5m6 14v-7m5 7H2"/>', settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',
  more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>', search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>', bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>', plus:'<path d="M12 5v14M5 12h14"/>', grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>', up:'<path d="m6 15 6-6 6 6"/>', arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>', shoe:'<path d="M3 14c4 0 5-5 6-9l3 5c2 2 5 3 8 3 1 0 2 1 2 2v2H3z"/>', undo:'<path d="m9 14-5-5 5-5"/><path d="M4 9h10a6 6 0 0 1 6 6v2"/>', download:'<path d="M12 3v12m-5-5 5 5 5-5"/><path d="M5 21h14"/>', sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>'
};
function hydrateIcons(scope = document){ $$('[data-icon]',scope).forEach((el)=>{ const name=el.dataset.icon; if(icons[name]) el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`; }); }

const state = { view:"pregled", dashboard:demoDashboard, inventory:[...demoInventory], sales:[...demoSales], customers:[...demoCustomers], products:[...new Map(demoInventory.map(i=>[i.product_name,{id:`p-${i.id}`,name:i.product_name,brand:i.brand}])).values()] };
const titles={pregled:["Nedjelja, 6. rujna","Dobro jutro, Bruno."],zaliha:["Tvoja roba","Zaliha"],prodaje:["Financije","Prodaje"],proizvodi:["Tvoj katalog","Proizvodi"],kupci:["Odnosi","Kupci"],troskovi:["Poslovanje","Troškovi"],izvjestaji:["Analitika","Izvještaji"],postavke:["Tvoj račun","Postavke"],vise:["Sve na jednom mjestu","Više"]};

function chartSvg(){return `<div class="hero-chart"><svg viewBox="0 0 700 150" preserveAspectRatio="none" aria-label="Graf dobiti zadnjih šest mjeseci"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7567f0"/><stop offset="1" stop-color="#7567f0" stop-opacity="0"/></linearGradient></defs><path class="chart-grid-line" d="M0 120H700M0 75H700M0 30H700"/><path class="chart-area" d="M0 123 C50 118 72 91 120 98 S185 113 230 86 S295 62 344 78 S405 102 457 58 S520 52 565 46 S635 16 700 20 L700 150H0Z"/><path class="chart-line" d="M0 123 C50 118 72 91 120 98 S185 113 230 86 S295 62 344 78 S405 102 457 58 S520 52 565 46 S635 16 700 20"/><circle class="chart-dot" cx="700" cy="20" r="4"/></svg></div><div class="chart-labels"><span>TRA</span><span>SVI</span><span>LIP</span><span>SRP</span><span>KOL</span><span>RUJ</span></div>`}
function dashboardView(){const d=state.dashboard,k=d.kpis,goal=d.settings.monthly_profit_goal_cents,progress=Math.min(100,Math.round(k.profit_month_cents/goal*100));const ageNames={"0_14":"0–14 dana","15_30":"15–30 dana","31_60":"31–60 dana","60_plus":"60+ dana"};return `<div class="dashboard-grid">
  <article class="card profit-hero"><p class="card-kicker">Dobit ovaj mjesec</p><div class="hero-value">${money(k.profit_month_cents)}</div><span class="change"><span data-icon="up"></span>21,4 % u odnosu na prošli mjesec</span>${chartSvg()}</article>
  <article class="card goal-card"><div><div class="goal-head"><div><p class="card-kicker">Mjesečni cilj</p><h3 class="goal-value">${money(k.profit_month_cents,0)} <span>/ ${money(goal,0)}</span></h3><p class="goal-copy">Još ${money(goal-k.profit_month_cents,0)} do cilja</p></div><button class="icon-button" data-view="postavke"><span data-icon="more"></span></button></div><div class="progress-ring"><svg viewBox="0 0 100 100"><circle class="track" cx="50" cy="50" r="40"/><circle class="fill" cx="50" cy="50" r="40" style="stroke-dashoffset:${251-(251*progress/100)}"/></svg><b>${progress}%</b></div></div><div><div class="progress-bar"><i style="width:${progress}%"></i></div><div class="goal-foot"><span>0 €</span><span>${money(goal,0)}</span></div></div></article>
  <section class="kpi-grid">${kpi("Prihod ovaj mjesec",money(k.revenue_month_cents),"+12,0 % prema kolovozu","chart")}${kpi("Vrijednost zalihe",money(k.inventory_value_cents),`${k.items_count} artikla na zalihi`,"box")}${kpi("Prodano ovaj mjesec",number(k.sold_month),"4 prodaje ovaj tjedan","bag")}${kpi("Prosječna dobit",money(k.avg_profit_cents),`${number(k.avg_roi)} % prosječni ROI`,"up")}</section>
  <article class="card wide-card inventory-age"><div class="section-head"><div><h2>Starost zalihe</h2><p>Vrijednost robe prema vremenu na zalihi</p></div><button class="text-button" data-view="zaliha">Prikaži zalihu</button></div><div class="age-bars">${d.age_buckets.map((row,i)=>`<div class="age-row"><span>${ageNames[row.bucket]}</span><div class="age-track"><i style="width:${[78,58,42,29][i]}%"></i></div><strong>${money(row.value_cents,0)}</strong></div>`).join("")}</div></article>
  <article class="card wide-card activity-card"><div class="section-head"><div><h2>Nedavna aktivnost</h2><p>Posljednje promjene</p></div><button class="text-button">Sve aktivnosti</button></div><div class="activity-list">${d.activity.map(activityRow).join("")}</div></article>
  <article class="card wide-card top-products"><div class="section-head"><div><h2>Top proizvodi</h2><p>Najuspješniji modeli ovaj mjesec</p></div><button class="text-button" data-view="proizvodi">Svi proizvodi</button></div>${d.top_products.map((p,i)=>`<div class="product-row"><div class="product-thumb">${i+1}</div><div class="product-info"><strong>${esc(p.name)}</strong><span>${esc(p.brand)}</span></div><div class="product-stat"><strong>${p.sold_count}</strong><span>prodano</span></div><div class="product-stat"><strong>${money(p.avg_profit_cents,0)}</strong><span>prosj. dobit</span></div><div class="product-stat"><strong>${number(p.roi)} %</strong><span>ROI</span></div></div>`).join("")}</article>
  </div>`}
function kpi(label,value,copy,icon){return `<article class="card kpi-card"><div class="kpi-top"><span>${label}</span><i class="kpi-icon" data-icon="${icon}"></i></div><h3>${value}</h3><p>${copy}</p></article>`}
function activityRow(a){const sale=a.action==="sale_created",m=a.metadata??{};return `<div class="activity-item"><i class="activity-icon ${sale?"":"add"}" data-icon="${sale?"bag":"plus"}"></i><div><strong>${esc(m.name??"Aktivnost")}${m.variant?`, ${esc(m.variant)}`:""}</strong><span>${sale?"Prodano":"Dodano na zalihu"} · ${new Date(a.created_at).toLocaleDateString("hr-HR",{day:"numeric",month:"short"})}</span></div><b class="${sale?"positive":""}">${sale?`+${money(m.profit_cents,0)}`:money(m.total_cost_cents,0)}</b></div>`}

function inventoryView(){return `${toolbar("Zaliha","Svaki fizički artikl prati se zasebno.","Dodaj artikl","inventory")}<div class="filter-row"><button class="filter-chip active">Svi artikli · ${state.inventory.length}</button><button class="filter-chip">0–14 dana</button><button class="filter-chip">15–30 dana</button><button class="filter-chip">31–60 dana</button><button class="filter-chip">60+ dana</button><button class="filter-chip">Najstarije prvo</button></div><div class="item-grid">${state.inventory.map(item=>`<article class="card inventory-card"><div class="item-image"><span data-icon="shoe"></span></div><div class="inventory-card-top"><div><h3>${esc(item.product_name)}</h3><p class="brand-label">${esc(item.brand)}</p></div><button class="icon-button" data-item-actions="${item.id}" aria-label="Radnje za ${esc(item.product_name)}"><span data-icon="more"></span></button></div><div class="item-meta"><span class="badge">Veličina ${esc(item.variant)}</span><span class="badge ${item.age_days>=60?"warning":""}">${item.age_days} dana</span></div><div class="item-prices"><div><span>UKUPNI TROŠAK</span><strong>${money(item.total_cost_cents)}</strong></div><button class="sell-button" data-quick-sale="${item.id}">Prodaj</button></div></article>`).join("")}</div>`}
function salesView(){return `${toolbar("Prodaje","Realna dobit nakon svih troškova.","Nova prodaja","sale")}<div class="filter-row"><button class="filter-chip active">Ovaj mjesec</button><button class="filter-chip">Prošli mjesec</button><button class="filter-chip">Sve vrijeme</button></div><article class="card table-card"><table class="data-table"><thead><tr><th>Artikl</th><th>Kupac</th><th>Prodajna cijena</th><th>Trošak</th><th>Dobit</th><th>Datum</th></tr></thead><tbody>${state.sales.map(s=>`<tr><td><div class="table-item-row"><div><span class="table-primary">${esc(s.product_name)}</span><span class="table-secondary">${esc(s.brand)} · ${esc(s.variant)}</span></div><button class="icon-button table-action" data-sale-actions="${s.id}" aria-label="Radnje za prodaju ${esc(s.product_name)}"><span data-icon="more"></span></button></div></td><td>${esc(s.customer_name??'—')}</td><td>${money(s.sale_price_cents)}</td><td>${money(s.true_cost_cents)}</td><td class="positive"><strong>${Number(s.profit_cents)>=0?'+':''}${money(s.profit_cents)}</strong></td><td>${new Date(s.sold_at).toLocaleDateString("hr-HR",{day:"numeric",month:"short"})}</td></tr>`).join("")}</tbody></table></article>`}
function productsView(){return `${toolbar("Proizvodi","Katalog modela neovisan o fizičkoj zalihi.","Novi proizvod","product")}<article class="card table-card"><table class="data-table"><thead><tr><th>Proizvod</th><th>Brand</th><th>Na zalihi</th><th>Ukupno prodano</th></tr></thead><tbody>${state.products.map((p,i)=>`<tr><td><span class="table-primary">${esc(p.name)}</span></td><td>${esc(p.brand)}</td><td>${[2,1,1,2,1,1][i]??0}</td><td>${[8,6,4,3,2,2][i]??0}</td></tr>`).join("")}</tbody></table></article>`}
function customersView(){return `${toolbar("Kupci","Vrijedni odnosi i povijest kupnji.","Novi kupac","customer")}<article class="card table-card"><table class="data-table"><thead><tr><th>Kupac</th><th>Tag</th><th>Kupnji</th><th>Ukupno potrošeno</th><th>Zadnja kupnja</th></tr></thead><tbody>${state.customers.map(c=>`<tr><td><span class="table-primary">${esc(c.name)}</span><span class="table-secondary">${esc(c.phone)}</span></td><td><span class="badge">${esc(c.tag)}</span></td><td>${c.purchases}</td><td>${money(c.spent_cents)}</td><td>${c.last_purchase}</td></tr>`).join("")}</tbody></table></article>`}
function expensesView(){return `${toolbar("Troškovi","Poslovni troškovi izvan nabave artikala.","Novi trošak","expense")}<section class="kpi-grid">${kpi("Troškovi ovaj mjesec",money(38420),"12 evidentiranih troškova","receipt")}${kpi("Dostava",money(12400),"32 % svih troškova","box")}${kpi("Ambalaža",money(5600),"15 % svih troškova","bag")}${kpi("Ostalo",money(20420),"53 % svih troškova","more")}</section><article class="card empty-card" style="margin-top:12px"><div class="empty-icon" data-icon="receipt"></div><h3>Svi troškovi su uredno evidentirani</h3><p>Dodaj novi trošak ili promijeni razdoblje za detaljan prikaz.</p></article>`}
function reportsView(){return `${toolbar("Izvještaji","Profesionalni financijski pregled na hrvatskom.","Preuzmi PDF","report")}<div class="filter-row"><button class="filter-chip active">Ovaj mjesec</button><button class="filter-chip">Prošli mjesec</button><button class="filter-chip">Sve vrijeme</button></div>${dashboardView()}`}
function settingsView(){return `${toolbar("Postavke","Prilagodi Stockd svom načinu rada.","Spremi promjene",null)}<div class="dashboard-grid"><article class="card wide-card"><div class="section-head"><div><h2>Izgled aplikacije</h2><p>Odaberi način prikaza</p></div></div><div class="filter-row"><button class="filter-chip" data-theme-choice="light">Svijetli</button><button class="filter-chip" data-theme-choice="dark">Tamni</button><button class="filter-chip active" data-theme-choice="system">Prema sustavu</button></div></article><article class="card wide-card"><div class="section-head"><div><h2>Članarina</h2><p>Pristup aplikaciji</p></div><span class="badge positive">Aktivna</span></div><h3 style="font-size:30px;margin:0">30,00 € <span style="font-size:12px;color:var(--muted);font-weight:500">mjesečno</span></h3><p style="font-size:11px;color:var(--muted);margin-top:8px">Vrijedi do 6. listopada 2026.</p></article></div>`}
function moreView(){return `<div class="page-toolbar"><div><h2>Više</h2><p>Svi dijelovi Stockda.</p></div></div><div class="item-grid">${[["proizvodi","tag","Proizvodi"],["kupci","users","Kupci"],["troskovi","receipt","Troškovi"],["izvjestaji","chart","Izvještaji"],["postavke","settings","Postavke"]].map(([view,icon,label])=>`<button class="card inventory-card" data-view="${view}" style="border:1px solid var(--line);text-align:left"><i class="action-icon violet" data-icon="${icon}"></i><h3 style="margin-top:14px">${label}</h3><p class="brand-label">Otvori ${label.toLowerCase()}</p></button>`).join("")}</div>`}
function toolbar(title,copy,button,form){return `<div class="page-toolbar"><div><h2>${title}</h2><p>${copy}</p></div>${button?`<button class="primary-button" ${form==='report'?'data-print':'data-open-form="'+form+'"'}><span data-icon="${form==='report'?'download':'plus'}"></span><span>${button}</span></button>`:""}</div>`}

const views={pregled:dashboardView,zaliha:inventoryView,prodaje:salesView,proizvodi:productsView,kupci:customersView,troskovi:expensesView,izvjestaji:reportsView,postavke:settingsView,vise:moreView};
function render(view=state.view){state.view=view; const [eyebrow,title]=titles[view]??titles.pregled; $("#eyebrow").textContent=eyebrow;$("#pageTitle").textContent=title;$("#appView").innerHTML=(views[view]??dashboardView)();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));hydrateIcons($("#appView")); bindDynamic();location.hash=view;}

function formMarkup(type,itemId){const editItem=state.inventory.find((item)=>item.id===itemId);if(type==='inventoryEdit'&&editItem){return `<div class="modal-head"><div><p>Uređivanje artikla</p><h2>${esc(editItem.product_name)}</h2></div><button class="icon-button" data-close-modal><span data-icon="close"></span></button></div><form id="entryForm" data-type="inventoryEdit"><input type="hidden" name="item_id" value="${esc(editItem.id)}"><div class="form-grid"><div class="field"><label>Veličina / varijanta</label><input name="variant" value="${esc(editItem.variant??'')}" required></div><div class="field"><label>Datum kupnje</label><input type="date" name="purchased_at" value="${esc(String(editItem.purchased_at??'2026-09-06').slice(0,10))}" required></div><div class="field"><label>Nabavna cijena (€)</label><input type="number" name="purchase_price" min="0" step="0.01" value="${Number(editItem.purchase_price_cents??0)/100}" required></div><div class="field"><label>Dostava (€)</label><input type="number" name="shipping" min="0" step="0.01" value="${Number(editItem.inbound_shipping_cents??0)/100}"></div><div class="field"><label>Authentication (€)</label><input type="number" name="authentication" min="0" step="0.01" value="${Number(editItem.authentication_fee_cents??0)/100}"></div><div class="field"><label>Ostali troškovi (€)</label><input type="number" name="additional" min="0" step="0.01" value="${Number(editItem.additional_cost_cents??0)/100}"></div><div class="field full"><label>Izvor / dobavljač</label><input name="source" value="${esc(editItem.source??'')}"></div><div class="field full"><label>Bilješka</label><textarea name="notes">${esc(editItem.notes??'')}</textarea></div><div class="calculated-total"><span>Realni trošak</span><strong id="trueCost">${money(editItem.total_cost_cents)}</strong></div></div><div class="form-actions"><button type="button" class="secondary-button" data-close-modal>Odustani</button><button class="primary-button">Spremi promjene</button></div></form>`}const products=state.products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("");const items=state.inventory.map(i=>`<option value="${i.id}" ${i.id===itemId?'selected':''}>${esc(i.product_name)} · ${esc(i.variant)} · ${money(i.total_cost_cents)}</option>`).join("");const config={
  inventory:["Dodaj na zalihu",`<div class="field full"><label>Proizvod</label><select name="product_id" required>${products}</select></div><div class="field"><label>Veličina / varijanta</label><input name="variant" placeholder="npr. 43" required></div><div class="field"><label>Datum kupnje</label><input type="date" name="purchased_at" value="2026-09-06"></div><div class="field"><label>Nabavna cijena (€)</label><input type="number" name="purchase_price" min="0" step="0.01" placeholder="0,00" required></div><div class="field"><label>Dostava (€)</label><input type="number" name="shipping" min="0" step="0.01" placeholder="0,00"></div><div class="field"><label>Authentication (€)</label><input type="number" name="authentication" min="0" step="0.01" placeholder="0,00"></div><div class="field"><label>Ostali troškovi (€)</label><input type="number" name="additional" min="0" step="0.01" placeholder="0,00"></div><div class="calculated-total"><span>Realni trošak</span><strong id="trueCost">0,00 €</strong></div>`],
  sale:["Nova prodaja",`<div class="field full"><label>Točan artikl</label><select name="inventory_item_id" required>${items}</select></div><div class="field"><label>Prodajna cijena (€)</label><input type="number" name="sale_price" min="0" step="0.01" required autofocus></div><div class="field"><label>Datum prodaje</label><input type="date" name="sold_at" value="2026-09-06"></div><div class="field"><label>Kupac (opcionalno)</label><input name="customer" placeholder="Ime kupca"></div><div class="field"><label>Platforma</label><select name="platform"><option>Instagram</option><option>Njuškalo</option><option>Direktno</option><option>StockX</option></select></div><div class="field"><label>Platform fee (€)</label><input type="number" name="platform_fee" min="0" step="0.01"></div><div class="field"><label>Dostava (€)</label><input type="number" name="outbound_shipping" min="0" step="0.01"></div>`],
  product:["Novi proizvod",`<div class="field full"><label>Naziv proizvoda</label><input name="name" placeholder="npr. Yeezy 350 V2 MX Bone" required autofocus></div><div class="field"><label>Brand</label><input name="brand" placeholder="Adidas"></div><div class="field"><label>Kategorija</label><select name="category"><option>Tenisice</option><option>Odjeća</option><option>Elektronika</option><option>Ostalo</option></select></div><div class="field"><label>SKU</label><input name="sku" placeholder="Opcionalno"></div><div class="field full"><label>Bilješka</label><textarea name="notes" placeholder="Detalji o proizvodu…"></textarea></div>`],
  expense:["Novi trošak",`<div class="field"><label>Kategorija</label><select name="category"><option>Dostava</option><option>Ambalaža</option><option>Gorivo</option><option>Authentication</option><option>Skladište</option><option>Ostalo</option></select></div><div class="field"><label>Iznos (€)</label><input type="number" name="amount" min="0" step="0.01" required autofocus></div><div class="field full"><label>Opis</label><input name="description" placeholder="Kratak opis troška" required></div><div class="field full"><label>Datum</label><input type="date" name="occurred_at" value="2026-09-06"></div>`],
  customer:["Novi kupac",`<div class="field full"><label>Ime i prezime</label><input name="name" required autofocus></div><div class="field"><label>Telefon</label><input name="phone"></div><div class="field"><label>Tag</label><select name="tag"><option>Stalni kupac</option><option>VIP</option><option>Wholesale</option><option>Instagram</option></select></div><div class="field full"><label>Adresa</label><input name="address"></div>`]
  }[type]??["Nova stavka",""];return `<div class="modal-head"><div><p>Stockd unos</p><h2>${config[0]}</h2></div><button class="icon-button" data-close-modal><span data-icon="close"></span></button></div><form id="entryForm" data-type="${type}"><div class="form-grid">${config[1]}</div><div class="form-actions"><button type="button" class="secondary-button" data-close-modal>Odustani</button><button class="primary-button">Spremi</button></div></form>`}
function openForm(type,itemId){closeSheet();$("#modalContent").innerHTML=formMarkup(type,itemId);$("#formModal").hidden=false;hydrateIcons($("#modalContent"));$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);$("#entryForm").onsubmit=submitForm;if(type==='inventory'||type==='inventoryEdit')$$('#entryForm input[type=number]').forEach(i=>i.oninput=updateTrueCost)}
function openItemActions(itemId){const item=state.inventory.find((row)=>row.id===itemId);if(!item)return;$("#modalContent").innerHTML=`<div class="modal-head"><div><p>Artikl na zalihi</p><h2>${esc(item.product_name)}</h2><p style="margin:7px 0 0;color:var(--muted);font-size:11px">Veličina ${esc(item.variant)} · ${money(item.total_cost_cents)}</p></div><button class="icon-button" data-close-modal><span data-icon="close"></span></button></div><div class="quick-action-grid"><button data-edit-item="${item.id}"><span class="action-icon violet" data-icon="settings"></span><strong>Uredi podatke</strong><small>Cijena, veličina i troškovi</small></button><button data-action-sale="${item.id}"><span class="action-icon green" data-icon="bag"></span><strong>Prodaj artikl</strong><small>Evidentiraj prodaju</small></button></div>`;$("#formModal").hidden=false;hydrateIcons($("#modalContent"));$('[data-close-modal]').onclick=closeModal;$('[data-edit-item]').onclick=()=>openForm('inventoryEdit',item.id);$('[data-action-sale]').onclick=()=>openForm('sale',item.id)}
function openSaleActions(saleId){const sale=state.sales.find((row)=>row.id===saleId);if(!sale)return;$("#modalContent").innerHTML=`<div class="modal-head"><div><p>Evidentirana prodaja</p><h2>${esc(sale.product_name)}</h2><p style="margin:7px 0 0;color:var(--muted);font-size:11px">${money(sale.sale_price_cents)} · ${new Date(sale.sold_at).toLocaleDateString('hr-HR')}</p></div><button class="icon-button" data-close-modal aria-label="Zatvori"><span data-icon="close"></span></button></div><div class="sale-summary"><div><span>Veličina</span><strong>${esc(sale.variant??'—')}</strong></div><div><span>Realna dobit</span><strong class="${Number(sale.profit_cents)>=0?'positive':'negative'}">${money(sale.profit_cents)}</strong></div></div><div class="warning-panel"><strong>Poništi prodaju</strong><p>Prodaja ostaje zabilježena u aktivnosti, a artikl se vraća na zalihu.</p></div><div class="form-actions"><button type="button" class="secondary-button" data-close-modal>Odustani</button><button type="button" class="danger-button" data-undo-sale="${sale.id}"><span data-icon="undo"></span>Poništi prodaju</button></div>`;$("#formModal").hidden=false;hydrateIcons($("#modalContent"));$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);$('[data-undo-sale]').onclick=()=>undoSaleAction(sale)}
async function undoSaleAction(sale){const button=$('[data-undo-sale]');button.disabled=true;button.textContent='Poništavanje…';try{if(demoMode){state.sales=state.sales.filter(row=>row.id!==sale.id);state.inventory.unshift({id:sale.inventory_item_id??crypto.randomUUID(),product_name:sale.product_name,brand:sale.brand,variant:sale.variant,total_cost_cents:sale.true_cost_cents,purchase_price_cents:sale.true_cost_cents,age_days:0})}else{await api(`/api/sales/${sale.id}/undo`,{method:'POST'});const [items,sales,dashboard]=await Promise.all([api('/api/inventory'),api('/api/sales'),api('/api/dashboard')]);state.inventory=items.items;state.sales=sales.sales;state.dashboard=dashboard}closeModal();render('prodaje');showToast('Prodaja je poništena, a artikl vraćen na zalihu.')}catch(error){showToast(error.message||'Prodaju nije moguće poništiti.');button.disabled=false;button.innerHTML='<span data-icon="undo"></span>Poništi prodaju';hydrateIcons(button)}}
function closeModal(){$("#formModal").hidden=true}
function updateTrueCost(){const f=$("#entryForm");const total=['purchase_price','shipping','authentication','additional'].reduce((s,n)=>s+(Number(f.elements[n]?.value)||0),0);$("#trueCost").textContent=new Intl.NumberFormat('hr-HR',{style:'currency',currency:'EUR'}).format(total)}
async function submitForm(event){
  event.preventDefault();
  const form=event.currentTarget,type=form.dataset.type,data=Object.fromEntries(new FormData(form));
  const submit=form.querySelector('button[type="submit"],button.primary-button:last-child');
  const euro=(value)=>Math.round((Number(value)||0)*100);
  if(submit){submit.disabled=true;submit.textContent='Spremanje…'}
  try{
    if(type==='inventory'){
      const product=state.products.find((item)=>item.id===data.product_id);
      const payload={product_id:data.product_id,variant:data.variant,purchase_price_cents:euro(data.purchase_price),inbound_shipping_cents:euro(data.shipping),authentication_fee_cents:euro(data.authentication),additional_cost_cents:euro(data.additional),purchased_at:data.purchased_at};
      const saved=demoMode?{id:crypto.randomUUID(),total_cost_cents:payload.purchase_price_cents+payload.inbound_shipping_cents+payload.authentication_fee_cents+payload.additional_cost_cents}:await api('/api/inventory',{method:'POST',body:JSON.stringify(payload)});
      state.inventory.unshift({id:saved.id,product_name:product?.name??'Artikl',brand:product?.brand??'',variant:data.variant,total_cost_cents:saved.total_cost_cents,purchase_price_cents:payload.purchase_price_cents,age_days:0});
    }else if(type==='inventoryEdit'){
      const item=state.inventory.find((row)=>row.id===data.item_id);
      if(!item)throw new Error('Artikl nije pronađen.');
      const payload={variant:data.variant,purchase_price_cents:euro(data.purchase_price),inbound_shipping_cents:euro(data.shipping),authentication_fee_cents:euro(data.authentication),additional_cost_cents:euro(data.additional),purchased_at:data.purchased_at,source:data.source,notes:data.notes};
      const saved=demoMode?{...payload,total_cost_cents:payload.purchase_price_cents+payload.inbound_shipping_cents+payload.authentication_fee_cents+payload.additional_cost_cents}:await api(`/api/inventory/${data.item_id}`,{method:'PATCH',body:JSON.stringify(payload)});
      Object.assign(item,saved,{variant:saved.variant??data.variant});
    }else if(type==='product'){
      const saved=demoMode?{id:crypto.randomUUID()}:await api('/api/products',{method:'POST',body:JSON.stringify(data)});
      state.products.unshift({id:saved.id,name:data.name,brand:data.brand});
    }else if(type==='sale'){
      const item=state.inventory.find((row)=>row.id===data.inventory_item_id);
      if(!item)throw new Error('Artikl nije pronađen. Osvježite stranicu i pokušajte ponovno.');
      const payload={inventory_item_id:data.inventory_item_id,sale_price_cents:euro(data.sale_price),platform:data.platform,platform_fee_cents:euro(data.platform_fee),outbound_shipping_cents:euro(data.outbound_shipping),sold_at:data.sold_at};
      const saved=demoMode?{id:crypto.randomUUID(),netProfitCents:payload.sale_price_cents-item.total_cost_cents-payload.platform_fee_cents-payload.outbound_shipping_cents}:await api('/api/sales',{method:'POST',body:JSON.stringify(payload)});
      state.sales.unshift({id:saved.id,product_name:item.product_name,brand:item.brand,variant:item.variant,sold_at:data.sold_at,sale_price_cents:payload.sale_price_cents,true_cost_cents:item.total_cost_cents,profit_cents:saved.netProfitCents,customer_name:data.customer||'—',platform:data.platform});
      state.inventory=state.inventory.filter((row)=>row.id!==item.id);
    }else if(type==='customer'){
      const saved=demoMode?{id:crypto.randomUUID()}:await api('/api/customers',{method:'POST',body:JSON.stringify(data)});
      state.customers.unshift({id:saved.id,name:data.name,phone:data.phone,purchases:0,spent_cents:0,tag:data.tag,last_purchase:'—'});
    }else if(type==='expense'&&!demoMode){
      await api('/api/expenses',{method:'POST',body:JSON.stringify({category:data.category,description:data.description,amount_cents:euro(data.amount),occurred_at:data.occurred_at})});
    }
    closeModal();showToast('Spremljeno.');
    render(type==='sale'?'prodaje':type==='inventory'||type==='inventoryEdit'?'zaliha':type==='customer'?'kupci':type==='product'?'proizvodi':type==='expense'?'troskovi':state.view);
  }catch(error){
    showToast(error.message||'Došlo je do greške.');
    if(submit){submit.disabled=false;submit.textContent='Spremi'}
  }
}

function openSheet(){$("#sheetBackdrop").hidden=false;$("#actionSheet").hidden=false}function closeSheet(){$("#sheetBackdrop").hidden=true;$("#actionSheet").hidden=true}function showToast(message){const toast=$("#toast");toast.textContent=message;toast.hidden=false;setTimeout(()=>toast.hidden=true,2600)}
function bindDynamic(){$$('[data-view]',$("#appView")).forEach(b=>b.onclick=()=>render(b.dataset.view));$$('[data-open-form]').forEach(b=>b.onclick=()=>openForm(b.dataset.openForm));$$('[data-quick-sale]').forEach(b=>b.onclick=()=>openForm('sale',b.dataset.quickSale));$$('[data-item-actions]').forEach(b=>b.onclick=()=>openItemActions(b.dataset.itemActions));$$('[data-sale-actions]').forEach(b=>b.onclick=()=>openSaleActions(b.dataset.saleActions));$('[data-print]')?.addEventListener('click',()=>window.print());$$('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice))}
function setTheme(theme){localStorage.setItem('stockd-theme',theme);const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme))}

function openSearch(){$("#searchPalette").hidden=false;$("#globalSearch").focus();renderSearch('')}function closeSearch(){$("#searchPalette").hidden=true}function renderSearch(query){const q=query.toLowerCase().trim();const source=[...state.inventory.map(x=>({title:x.product_name,subtitle:`Zaliha · veličina ${x.variant}`,icon:'box',view:'zaliha'})),...state.customers.map(x=>({title:x.name,subtitle:`Kupac · ${x.phone}`,icon:'users',view:'kupci'})),...state.sales.map(x=>({title:x.product_name,subtitle:`Prodaja · ${x.customer_name}`,icon:'bag',view:'prodaje'}))];const rows=(q?source.filter(x=>(x.title+x.subtitle).toLowerCase().includes(q)):source.slice(0,5)).slice(0,10);$("#searchResults").innerHTML=rows.length?rows.map(x=>`<button class="search-result" data-result-view="${x.view}"><i class="result-icon" data-icon="${x.icon}"></i><div><strong>${esc(x.title)}</strong><small>${esc(x.subtitle)}</small></div></button>`).join(''):`<div class="empty-card"><p>Nema rezultata za “${esc(query)}”.</p></div>`;hydrateIcons($("#searchResults"));$$('[data-result-view]').forEach(b=>b.onclick=()=>{render(b.dataset.resultView);closeSearch()})}

async function loadData(){if(demoMode)return;try{const [dash,items,saleList,productList,customerList]=await Promise.all([api('/api/dashboard'),api('/api/inventory'),api('/api/sales'),api('/api/products'),api('/api/customers')]);state.dashboard=dash;state.inventory=items.items;state.sales=saleList.sales;state.products=productList.products;state.customers=customerList.customers;render()}catch(error){if(error.status===401)location.href='login.html';else if(error.status===402)location.href='expired.html';else showToast(error.message)}}

hydrateIcons();setTheme(localStorage.getItem('stockd-theme')||'system');render(location.hash.slice(1)||'pregled');loadData();
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.view)));$("#quickAdd").onclick=openSheet;$("#sheetBackdrop").onclick=closeSheet;$$('[data-close-sheet]').forEach(b=>b.onclick=closeSheet);$$('[data-form]').forEach(b=>b.onclick=()=>openForm(b.dataset.form));$("#searchTrigger").onclick=openSearch;$("#searchPalette").addEventListener('click',e=>{if(e.target===$("#searchPalette"))closeSearch()});$("#globalSearch").oninput=e=>renderSearch(e.target.value);addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){closeSearch();closeModal();closeSheet()}});addEventListener('offline',()=>$("#offlineBanner").hidden=false);addEventListener('online',()=>$("#offlineBanner").hidden=true);
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$("#updateBanner").hidden=false})})});$("#refreshApp").onclick=()=>location.reload()}
